# Generated by Django 5.2 on 2025-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='images',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
