# Generated by Django 5.2 on 2025-06-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_travelpost_images_travelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='video',
            field=models.FileField(blank='True', null='True', upload_to='videos'),
            preserve_default='True',
        ),
    ]
