# Generated by Django 5.2 on 2025-07-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/user_profile.png', null=True, upload_to='profile_pic/'),
        ),
    ]
